name: gsi_insight
description: "GSI Insight"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.3
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  fluttertoast: ^8.2.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
